# Crime compressor

This notebook is

In [1]:
import pandas as pd
import numpy as np

In [10]:
# police budget from 2001 to 2010; from annual reports
police_budget = [940936247, 1014762072, 1051226834, 1073131416, 1066250557,
                 1217401602, 1247932269, 1217139440, 1234586462, 1242139543]

In [11]:
# police personnel from 2001 to 2010; from annual reports
police_personnel = [16742, 16473, 16244, 15675, 15533,
                    15661, 15493, 15317, 14973, 13857]

In [9]:
df = pd.read_csv("Crimes_-_2001_to_present.csv", usecols=[5,8, 17],
                 dtype = {"Year": pd.np.int64, "Primary.Type" : pd.np.object, "Arrest" : pd.np.bool_})

In [12]:
crime_count = {}
crimes = ["HOMICIDE", "ASSAULT", "THEFT",
          "NARCOTICS", "BURGLARY", "BATTERY",
          "CRIM SEXUAL ASSAULT", "ARSON",
          "MOTOR VEHICLE THEFT", "PROSTITUTION",
          "CRIMINAL DAMAGE", "ARRESTS", "ALL"]

In [15]:
for i in range(2001,2011):
    crime_count[i] = [0]*len(crimes)

In [16]:
for i in df.iterrows():
    if i[1]["Year"] > 2010:
        continue
    for j in range(len(crimes)-1):
        if i[1]["Primary Type"] == crimes[j]:
            crime_count[i[1]["Year"]][j] += 1
    if i[1]["Arrest"] == True:
        crime_count[i[1]["Year"]][len(crimes)-2] += 1
    crime_count[i[1]["Year"]][len(crimes)-1] += 1

In [17]:
crime_list = []
k = 0
for i in crime_count.items():
    crime_list.append([i[0]])
    for j in range(len(crimes)):
        crime_list[k].append(i[1][j])
    k += 1

In [18]:
crime_df = pd.DataFrame(crime_list, columns=['Year'] + crimes)
crime_df = crime_df.dropna()

In [19]:
crime_df['Police Personnel'] = pd.Series(np.array(police_personnel), index = crime_df.index)
crime_df['Police Budget'] = pd.Series(np.array(police_budget), index = crime_df.index)

In [20]:
crime_df

,Year,HOMICIDE,ASSAULT,THEFT,NARCOTICS,BURGLARY,BATTERY,CRIM SEXUAL ASSAULT,ARSON,MOTOR VEHICLE THEFT,PROSTITUTION,CRIMINAL DAMAGE,ARRESTS,ALL,Police Personnel,Police Budget
0,2001,667,31383,99263,50567,26011,93448,1792,1010,27549,6026,55851,141833,485692,16742,940936247
1,2002,657,31521,98326,51789,25623,94154,1820,1032,25121,6408,55940,141419,486703,16473,1014762072
2,2003,604,29478,98875,54288,25157,88378,1584,955,22748,6214,55012,141539,475864,16244,1051226834
3,2004,454,28850,95461,57060,24564,87134,1551,778,22805,7476,53164,144654,469272,15675,1073131416
4,2005,453,27066,85683,56234,25504,83964,1524,691,22497,6124,54548,140877,453553,15533,1066250557
5,2006,477,25945,86234,55811,24324,80666,1443,726,21817,7034,57124,135353,447900,15661,1217401602
6,2007,448,26315,85152,54454,24858,79593,1508,712,18573,6087,53749,131807,436761,15493,1247932269
7,2008,513,25447,88429,46506,26219,75920,1501,644,18881,5141,52841,109924,426831,15317,1217139440
8,2009,460,22861,80970,43540,26766,68463,1385,616,15482,3940,47724,110710,392399,14973,1234586462
9,2010,438,21535,76742,43389,26422,65399,1328,522,19028,2485,40652,100360,369940,13857,1242139543

In [32]:
crime_df_dev = crime_df.copy(deep=True)

In [33]:
for k in crime_df_dev.columns[1:]:
    column_mean = np.mean(crime_df[k])
    for m in range(len(crime_df)):
        crime_df_dev[k].iloc[m] = 100.0*(crime_df_dev[k].iloc[m] - column_mean) / column_mean

In [34]:
crime_df_dev

,Year,HOMICIDE,ASSAULT,THEFT,NARCOTICS,BURGLARY,BATTERY,CRIM SEXUAL ASSAULT,ARSON,MOTOR VEHICLE THEFT,PROSTITUTION,CRIMINAL DAMAGE,ARRESTS,ALL,Police Personnel,Police Budget
0,2001,28.988590,16.060961,10.891653,-1.551287,1.825029,14.362779,16.092252,31.407754,28.432968,5.839993,6.058621,9.230359,9.269131,7.342532,-16.771862
1,2002,27.054728,16.571314,9.844884,0.827820,0.306129,15.226791,17.906193,34.270101,17.113673,12.549398,6.227628,8.911524,9.496582,5.617819,-10.241786
2,2003,16.805260,9.015869,10.458199,5.693115,-1.518117,8.158053,2.617258,24.251887,6.050788,9.142004,4.465396,9.003940,7.058065,4.149569,-7.016387
3,2004,-12.202669,6.693392,6.644249,11.089912,-3.839529,6.635631,0.479399,1.223003,6.316521,31.307632,0.956125,11.402906,5.575022,0.501385,-5.078873
4,2005,-12.396055,0.095784,-4.279243,9.481775,-0.159719,2.756147,-1.269759,-10.096279,4.880630,7.561254,3.584280,8.494112,2.038622,-0.409058,-5.687502
5,2006,-7.754786,-4.049911,-3.663693,8.658238,-4.779055,-1.279985,-6.517232,-5.542545,1.710482,23.544393,8.475992,4.239894,0.766831,0.411623,7.682182
6,2007,-13.362986,-2.681573,-4.872449,6.016299,-2.688610,-2.593135,-2.306297,-7.364039,-13.412991,6.911390,2.067014,1.509000,-1.739178,-0.665521,10.382695
7,2008,-0.792883,-5.891620,-1.211549,-9.457634,2.639285,-7.088196,-2.759782,-16.211293,-11.977100,-9.704048,0.342762,-15.343834,-3.973192,-1.793958,7.658993
8,2009,-11.042352,-15.455194,-9.544370,-15.232128,4.780621,-16.214162,-10.274683,-19.854281,-27.823180,-30.798279,-9.374199,-14.738509,-11.719572,-3.999538,9.202225
9,2010,-15.296848,-20.359022,-14.267680,-15.526110,3.433967,-19.963922,-13.967349,-32.084309,-11.291789,-56.353737,-22.803619,-22.709392,-16.772312,-11.154852,9.870314

In [35]:
crime_df_dev.to_csv(path_or_buf="crime_deviations.csv", index=False)